const topics = [{
        id: 1,
        imagesrc: 'img/topics-newbusiness.png',
        heading: 'New Business',
        textValue: 'Starting or buying a new business isn’t for the faint of heart. Use our connections and resources anytime.',
        backgroundColor: 'orchid',
        contentColor: 'orchid',
    },
    {
        id: 2,
        imagesrc: 'img/topics-parenting.png',
        heading: 'Parenting',
        textValue: 'Let’s face it – parenting is challenging in oh-so-many ways. We can connect you with people and resources to help every step of the way.',
        backgroundColor: 'tan',
        contentColor: 'tan',
    }, {
        id: "3",
        contentColor: "sage",
        imagesrc: "img/topics-military.png",
        heading: "Military Life Transitions",
        textValue: "From deployments to reintegration, military life presents challenges that can be overwhelming. You aren’t alone.",
    },
    {
        id: "4",
        contentColor: "blue",
        imagesrc: "img/topics-union.png",
        heading: "Marriage or Union",
        textValue: "From deployments to reintegration, military life presents challenges that can be overwhelming. You aren’t alone.",
    },
    {
        id: "5",
        contentColor: "orchid",
        imagesrc: "img/topics-careerchange.png",
        heading: "Job / Career Change",
        textValue: "Losing or changing your job or career can shake your world. Our resources can keep you grounded and connected.",
    },
    {
        id: "6",
        contentColor: "tan",
        imagesrc: "img/topics-community.png",
        heading: "Community",
        textValue: "Looking for a place where you can feel safe and welcomed? Find your community and sense of belonging.",
    },
    {
        id: "7",
        contentColor: "sage",
        imagesrc: "img/topics-humantrafficking.png",
        heading: "Human Trafficking",
        textValue: "Life and health after human trafficking? Absolutely. Heal and rebuild your life with other survivors.",
    },
    {
        id: "8",
        contentColor: "blue",
        imagesrc: "img/topics-homelessness.png",
        heading: "Homelessness",
        textValue: "Find hope and resources to manage the daily challenges, and find a path to get back on your feet.",
    },
    {
        id: "9",
        contentColor: "orchid",
        imagesrc: "img/topics-healthcrisis.png",
        heading: "Health Crisis",
        textValue: "A health crisis can turn your world upside down. We help you turn fear and uncertainty into hope and knowledge!",
    },
    {
        id: "10",
        contentColor: "tan",
        imagesrc: "img/topics-grieving.png",
        heading: "Grieving",
        textValue: "Losing someone or something dear can be crushing. Good grieving in community is an important part of healing.",
    },
    {
        id: "11",
        contentColor: "sage",
        imagesrc: "img/topics-selfawareness.png",
        heading: "Emerging Self-Awareness",
        textValue: "Many of us “go through the motions” early in life, but what happens when you get a wakeup call? We can help.",
    },
    {
        id: "12",
        contentColor: "blue",
        imagesrc: "img/topics-divorce.png",
        heading: "Divorce or Uncoupling",
        textValue: "Endings are realy hard and they affect everyone around us. Recover and heal with our connections & resources.",
    },
    {
        id: "13",
        contentColor: "orchid",
        imagesrc: "img/topics-comingofage.png",
        heading: "Coming of Age Ceremonies",
        textValue: "Level up into adolescence or young adulthood with intention, grace, community … and a celebration!",
    },
    {
        id: "14",
        contentColor: "tan",
        imagesrc: "img/topics-aging.png",
        heading: "Aging",
        textValue: "Have you gained wisdom and experience with your years? Share your “gold” with the community!",
    },
    {
        id: "15",
        contentColor: "sage",
        imagesrc: "img/topics-addiction.png",
        heading: "Addiction",
        textValue: "Whatever form of addiction you’re recovering from, you are not alone and our community can help.",
    },
    {
        id: "16",
        contentColor: "blue",
        imagesrc: "img/topics-abuse.png",
        heading: "Abuse",
        textValue: "Survivors of abuse and/or domestic violence CAN heal and become thrivers. You can do this!",
    },
]